#!/bin/bash

sed -i "s/set(BINARY $.*/set(BINARY \${BINDIR}\/$1\.cpp)/" ./CMakeLists.txt
cd build
cmake ../
make -j
cd ..
echo "
----------------------------------------------------
"
./build/"$1" "$2" "$3" "$4"
